### PR TITLE
Food Network - New Code

### PR DESCRIPTION
**Pull request by shopgirl284**
Updated code to reflect similar website design between Food Network and HGTV

### CODE REVIEW

**Comment by burgertime78** [comment]
Shopgirl284, the HGTV channel is now working, but the Food Network remains broken - "No full episodes"

**Comment by sander1** [comment]
@burgertime78 If you're not manually updating the code then it will not work until the moment the updated code from the pull request is pulled in and an updated channel bundle is pushed out to the Plex channel directory. Both those things just happened :)

**Comment by burgertime78** [comment]
Not super tech-saavy, and definitely don't know how to merge code, etc...  But what I *did* do after reading your response, was go into my plex media server, and click "check updates" for the channels, to which it reported that everything was up to date.  I then tried to load the full episodes on Food Network, and it did not work.  What on earth have I done wrong?

**Comment by burgertime78** [comment]
Thanks!  Working now.

**Comment by josephrooks** [comment]
@sander1 Seems like it still isn't working after updating my plugins. The HGTV app also doesn't seem to be working along with it.

**Comment by sander1** [comment]
I can't find anything not working... Make sure you are on Plex Media Server version 1.0 +. Older versions did not update the Service bundle automatically. Try quiting PMS, then removing the channels (manually if necessary).

**Pull request merged**
